source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

project 'YukonVaccinationVerifier', {
  'DEV' => :debug,
  'TST' => :release,
  'STG' => :release,
  'PROD' => :release, 
}

target 'YukonVaccinationVerifier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YukonVaccinationVerifier

  pod 'BCVaccineValidator', :git => 'https://github.com/AfsarFresh/iOSVaccineValidator.git', :tag => 'YVV_V_1_2_1_B_1'

  # pod 'BCVaccineValidator', :git => 'https://github.com/AfsarFresh/iOSVaccineValidator.git', :branch => 'timeBetweenDosesAndYukonExemptions'
  
end

# Make all installed pods use a deployment target of 11.0.
post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
